Sapi
GNS-Science/eq-fault-geom pull request #12
Opened 2020-09-01 02:21 UTC by sapikara

Updating README.md and setup.py and adding requirement.py.

2020-09-01 02:34 UTC, andy22b reviewed
Looks good. I'm not sure we need the xml files included? They are PyCharm specific...

2020-09-01 04:35 UTC, chrisbc commented on README.md
> +mkdir eq-fault-geom/ENV
IN hindsight these two lines are best left out. I will remove them from the other project too.

2020-09-01 04:48 UTC, chrisbc requested changes
Hi Sapi, 

 - I like the info about how setup.py and requirements.txt are different. 
 - I usually run the tests like nosetests, but this seems more canonical
 - I made a comment about some lines added into readme. 
 - adding the .idea folder hmmm... I don't think this should be part of the project, as it's distracting for non idea users. And who knows -  your settings may conflict with other .idea users?
 - there is already a .gitignore file in the project 

Can you make your changes on the sapi branch and request another review please. Then I'll 
checkout your work and try it out :)

2020-09-08 21:10 UTC, chrisbc approved these changes
:+1:

2020-09-08 21:12 UTC, chrisbc approved these changes
:+1:

2020-09-08 21:12 UTC, merged