Sapi testing
GNS-Science/eq-fault-geom pull request #42
Opened 2020-11-10 00:57 UTC by sapikara

Andy can now check the unit tests of test_cmf_faults.py.

2021-03-10 01:42 UTC, andy22b commented on src/eq_fault_geom/geomio/test_cfm_faults.py
> -        self.assertEqual(self.cmf_fault.dip_dir, 330.15406806735484)
You should use assertAlmostEqual here. The old value works fine on my machine.

2021-03-10 01:43 UTC, andy22b commented on src/eq_fault_geom/geomio/test_cfm_faults.py
> -        self.assertEqual(self.cmf_fault.dip_dir, 150.1540680673612)
assertAlmostEqual

2021-03-10 01:44 UTC, andy22b requested changes
We need to use assertAlmostEqual to address differences associated with different machines.

2021-03-17 03:54 UTC, sapikara commented on src/eq_fault_geom/geomio/test_cfm_faults.py
> -        self.assertEqual(self.cmf_fault.dip_dir, 150.1540680673612)
done - Thanks

2021-03-17 21:41 UTC, closed without merging